package com.parallax.hdvideo.wallpapers.ui.list

enum class AppScreen {
    HOME, CATEGORY, FAVORITE, DOWNLOAD, SEARCH, PLAYLIST, LOCAL, DETAIL, COUPLE, TOP_10_DEVICE, TRENDING, HOME_HASH_TAG, TOP_DOWNLOAD, BEST_HASH_TAG, NOTIFY, COLLECTION, PARALLAX;
}